FROM python:3.13-slim
WORKDIR /app
COPY ui/streamlit/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY ui/streamlit/app.py .
EXPOSE 8501
ENTRYPOINT ["streamlit", "run", "app.py", "--server.address=0.0.0.0"]

