// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chat.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (session_id, role, content, rewritten_query)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, role, content, rewritten_query, created_at
`

type CreateChatMessageParams struct {
	SessionID      uuid.UUID   `json:"session_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	RewrittenQuery pgtype.Text `json:"rewritten_query"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.RewrittenQuery,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.RewrittenQuery,
		&i.CreatedAt,
	)
	return i, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateChatSessionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Title  string    `json:"title"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession, arg.UserID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCitation = `-- name: CreateCitation :one
INSERT INTO citations (
    message_id,
    chunk_id,
    document_id,
    document_name,
    page_number,
    excerpt,
    dense_score,
    lexical_rank,
    fused_rank,
    rerank_score,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, message_id, chunk_id, document_id, document_name, page_number, excerpt, dense_score, lexical_rank, fused_rank, rerank_score, metadata, created_at
`

type CreateCitationParams struct {
	MessageID    uuid.UUID     `json:"message_id"`
	ChunkID      pgtype.UUID   `json:"chunk_id"`
	DocumentID   pgtype.UUID   `json:"document_id"`
	DocumentName string        `json:"document_name"`
	PageNumber   pgtype.Int4   `json:"page_number"`
	Excerpt      string        `json:"excerpt"`
	DenseScore   pgtype.Float8 `json:"dense_score"`
	LexicalRank  pgtype.Int4   `json:"lexical_rank"`
	FusedRank    pgtype.Int4   `json:"fused_rank"`
	RerankScore  pgtype.Float8 `json:"rerank_score"`
	Metadata     []byte        `json:"metadata"`
}

func (q *Queries) CreateCitation(ctx context.Context, arg CreateCitationParams) (Citation, error) {
	row := q.db.QueryRow(ctx, createCitation,
		arg.MessageID,
		arg.ChunkID,
		arg.DocumentID,
		arg.DocumentName,
		arg.PageNumber,
		arg.Excerpt,
		arg.DenseScore,
		arg.LexicalRank,
		arg.FusedRank,
		arg.RerankScore,
		arg.Metadata,
	)
	var i Citation
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ChunkID,
		&i.DocumentID,
		&i.DocumentName,
		&i.PageNumber,
		&i.Excerpt,
		&i.DenseScore,
		&i.LexicalRank,
		&i.FusedRank,
		&i.RerankScore,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createRetrievalTrace = `-- name: CreateRetrievalTrace :one
INSERT INTO retrieval_traces (
    user_id,
    session_id,
    original_query,
    rewritten_query,
    top_k,
    reranker_enabled,
    dense_hits,
    lexical_hits,
    fused_hits,
    reranked_hits,
    prompt_preview,
    latency_ms,
    estimated_cost_usd
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, user_id, session_id, original_query, rewritten_query, top_k, reranker_enabled, dense_hits, lexical_hits, fused_hits, reranked_hits, prompt_preview, latency_ms, estimated_cost_usd, created_at
`

type CreateRetrievalTraceParams struct {
	UserID           uuid.UUID   `json:"user_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	OriginalQuery    string      `json:"original_query"`
	RewrittenQuery   string      `json:"rewritten_query"`
	TopK             int32       `json:"top_k"`
	RerankerEnabled  bool        `json:"reranker_enabled"`
	DenseHits        []byte      `json:"dense_hits"`
	LexicalHits      []byte      `json:"lexical_hits"`
	FusedHits        []byte      `json:"fused_hits"`
	RerankedHits     []byte      `json:"reranked_hits"`
	PromptPreview    string      `json:"prompt_preview"`
	LatencyMs        int32       `json:"latency_ms"`
	EstimatedCostUsd string      `json:"estimated_cost_usd"`
}

func (q *Queries) CreateRetrievalTrace(ctx context.Context, arg CreateRetrievalTraceParams) (RetrievalTrace, error) {
	row := q.db.QueryRow(ctx, createRetrievalTrace,
		arg.UserID,
		arg.SessionID,
		arg.OriginalQuery,
		arg.RewrittenQuery,
		arg.TopK,
		arg.RerankerEnabled,
		arg.DenseHits,
		arg.LexicalHits,
		arg.FusedHits,
		arg.RerankedHits,
		arg.PromptPreview,
		arg.LatencyMs,
		arg.EstimatedCostUsd,
	)
	var i RetrievalTrace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.OriginalQuery,
		&i.RewrittenQuery,
		&i.TopK,
		&i.RerankerEnabled,
		&i.DenseHits,
		&i.LexicalHits,
		&i.FusedHits,
		&i.RerankedHits,
		&i.PromptPreview,
		&i.LatencyMs,
		&i.EstimatedCostUsd,
		&i.CreatedAt,
	)
	return i, err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, title, created_at, updated_at
FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type GetChatSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, role, content, rewritten_query, created_at
FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.RewrittenQuery,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
