// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: costs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTokenCostEvent = `-- name: CreateTokenCostEvent :one
INSERT INTO token_cost_events (
    user_id,
    document_id,
    chat_session_id,
    eval_run_id,
    provider,
    model,
    operation,
    input_tokens,
    output_tokens,
    estimated_cost_usd
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, document_id, chat_session_id, eval_run_id, provider, model, operation, input_tokens, output_tokens, estimated_cost_usd, created_at
`

type CreateTokenCostEventParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	DocumentID       pgtype.UUID `json:"document_id"`
	ChatSessionID    pgtype.UUID `json:"chat_session_id"`
	EvalRunID        pgtype.UUID `json:"eval_run_id"`
	Provider         string      `json:"provider"`
	Model            string      `json:"model"`
	Operation        string      `json:"operation"`
	InputTokens      int32       `json:"input_tokens"`
	OutputTokens     int32       `json:"output_tokens"`
	EstimatedCostUsd string      `json:"estimated_cost_usd"`
}

func (q *Queries) CreateTokenCostEvent(ctx context.Context, arg CreateTokenCostEventParams) (TokenCostEvent, error) {
	row := q.db.QueryRow(ctx, createTokenCostEvent,
		arg.UserID,
		arg.DocumentID,
		arg.ChatSessionID,
		arg.EvalRunID,
		arg.Provider,
		arg.Model,
		arg.Operation,
		arg.InputTokens,
		arg.OutputTokens,
		arg.EstimatedCostUsd,
	)
	var i TokenCostEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DocumentID,
		&i.ChatSessionID,
		&i.EvalRunID,
		&i.Provider,
		&i.Model,
		&i.Operation,
		&i.InputTokens,
		&i.OutputTokens,
		&i.EstimatedCostUsd,
		&i.CreatedAt,
	)
	return i, err
}
