// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countChunksByDocument = `-- name: CountChunksByDocument :one
SELECT count(*)
FROM chunks
WHERE document_id = $1
`

func (q *Queries) CountChunksByDocument(ctx context.Context, documentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChunksByDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChunk = `-- name: CreateChunk :one
INSERT INTO chunks (document_id, chunk_index, content, page_number, token_count, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, chunk_index, content, page_number, token_count, metadata, created_at
`

type CreateChunkParams struct {
	DocumentID uuid.UUID   `json:"document_id"`
	ChunkIndex int32       `json:"chunk_index"`
	Content    string      `json:"content"`
	PageNumber pgtype.Int4 `json:"page_number"`
	TokenCount int32       `json:"token_count"`
	Metadata   []byte      `json:"metadata"`
}

type CreateChunkRow struct {
	ID         uuid.UUID          `json:"id"`
	DocumentID uuid.UUID          `json:"document_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	PageNumber pgtype.Int4        `json:"page_number"`
	TokenCount int32              `json:"token_count"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) (CreateChunkRow, error) {
	row := q.db.QueryRow(ctx, createChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.PageNumber,
		arg.TokenCount,
		arg.Metadata,
	)
	var i CreateChunkRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.PageNumber,
		&i.TokenCount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    owner_user_id,
    filename,
    content_type,
    size_bytes,
    sha256,
    raw_bytes,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, 'uploaded'
)
RETURNING id, owner_user_id, filename, content_type, size_bytes, sha256, status, error_message, created_at, updated_at
`

type CreateDocumentParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Filename    string    `json:"filename"`
	ContentType string    `json:"content_type"`
	SizeBytes   int64     `json:"size_bytes"`
	Sha256      string    `json:"sha256"`
	RawBytes    []byte    `json:"raw_bytes"`
}

type CreateDocumentRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (CreateDocumentRow, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OwnerUserID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.RawBytes,
	)
	var i CreateDocumentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createIndexingJob = `-- name: CreateIndexingJob :one
INSERT INTO indexing_jobs (document_id, status)
VALUES ($1, 'queued')
RETURNING id, document_id, status, attempts, max_attempts, error_message, locked_at, locked_by, run_after, created_at, updated_at
`

func (q *Queries) CreateIndexingJob(ctx context.Context, documentID uuid.UUID) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, createIndexingJob, documentID)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChunksByDocument = `-- name: DeleteChunksByDocument :exec
DELETE FROM chunks
WHERE document_id = $1
`

func (q *Queries) DeleteChunksByDocument(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChunksByDocument, documentID)
	return err
}

const getChunkByVectorID = `-- name: GetChunkByVectorID :one
SELECT c.id, c.document_id, c.chunk_index, c.content, c.page_number, c.token_count, c.metadata, c.created_at,
       d.filename
FROM chunks c
JOIN documents d ON d.id = c.document_id
WHERE c.document_id = $1 AND c.chunk_index = $2
`

type GetChunkByVectorIDParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	ChunkIndex int32     `json:"chunk_index"`
}

type GetChunkByVectorIDRow struct {
	ID         uuid.UUID          `json:"id"`
	DocumentID uuid.UUID          `json:"document_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	PageNumber pgtype.Int4        `json:"page_number"`
	TokenCount int32              `json:"token_count"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Filename   string             `json:"filename"`
}

func (q *Queries) GetChunkByVectorID(ctx context.Context, arg GetChunkByVectorIDParams) (GetChunkByVectorIDRow, error) {
	row := q.db.QueryRow(ctx, getChunkByVectorID, arg.DocumentID, arg.ChunkIndex)
	var i GetChunkByVectorIDRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ChunkIndex,
		&i.Content,
		&i.PageNumber,
		&i.TokenCount,
		&i.Metadata,
		&i.CreatedAt,
		&i.Filename,
	)
	return i, err
}

const getDocumentByHash = `-- name: GetDocumentByHash :one
SELECT id, owner_user_id, filename, content_type, size_bytes, sha256, status, error_message, created_at, updated_at
FROM documents
WHERE owner_user_id = $1 AND sha256 = $2 AND status <> 'deleted'
`

type GetDocumentByHashParams struct {
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Sha256      string    `json:"sha256"`
}

type GetDocumentByHashRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDocumentByHash(ctx context.Context, arg GetDocumentByHashParams) (GetDocumentByHashRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByHash, arg.OwnerUserID, arg.Sha256)
	var i GetDocumentByHashRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByIDAndOwner = `-- name: GetDocumentByIDAndOwner :one
SELECT id, owner_user_id, filename, content_type, size_bytes, sha256, status, error_message, created_at, updated_at
FROM documents
WHERE id = $1 AND owner_user_id = $2 AND status <> 'deleted'
`

type GetDocumentByIDAndOwnerParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

type GetDocumentByIDAndOwnerRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDocumentByIDAndOwner(ctx context.Context, arg GetDocumentByIDAndOwnerParams) (GetDocumentByIDAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByIDAndOwner, arg.ID, arg.OwnerUserID)
	var i GetDocumentByIDAndOwnerRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentBytes = `-- name: GetDocumentBytes :one
SELECT id, owner_user_id, filename, content_type, size_bytes, sha256, raw_bytes, status, error_message, created_at, updated_at
FROM documents
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) GetDocumentBytes(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBytes, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.RawBytes,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsByOwner = `-- name: ListDocumentsByOwner :many
SELECT id, owner_user_id, filename, content_type, size_bytes, sha256, status, error_message, created_at, updated_at
FROM documents
WHERE owner_user_id = $1 AND status <> 'deleted'
ORDER BY created_at DESC
`

type ListDocumentsByOwnerRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDocumentsByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]ListDocumentsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByOwnerRow
	for rows.Next() {
		var i ListDocumentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Sha256,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentDeleted = `-- name: MarkDocumentDeleted :exec
UPDATE documents
SET status = 'deleted', updated_at = now()
WHERE id = $1 AND owner_user_id = $2
`

type MarkDocumentDeletedParams struct {
	ID          uuid.UUID `json:"id"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
}

func (q *Queries) MarkDocumentDeleted(ctx context.Context, arg MarkDocumentDeletedParams) error {
	_, err := q.db.Exec(ctx, markDocumentDeleted, arg.ID, arg.OwnerUserID)
	return err
}

const markDocumentStatus = `-- name: MarkDocumentStatus :one
UPDATE documents
SET status = $2, error_message = $3, updated_at = now()
WHERE id = $1
RETURNING id, owner_user_id, filename, content_type, size_bytes, sha256, status, error_message, created_at, updated_at
`

type MarkDocumentStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

type MarkDocumentStatusRow struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MarkDocumentStatus(ctx context.Context, arg MarkDocumentStatusParams) (MarkDocumentStatusRow, error) {
	row := q.db.QueryRow(ctx, markDocumentStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i MarkDocumentStatusRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
