// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const leaseIndexingJobs = `-- name: LeaseIndexingJobs :many
UPDATE indexing_jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_at = now(),
    locked_by = $2,
    updated_at = now()
WHERE id IN (
    SELECT id
    FROM indexing_jobs
    WHERE status = 'queued'
      AND run_after <= now()
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, document_id, status, attempts, max_attempts, error_message, locked_at, locked_by, run_after, created_at, updated_at
`

type LeaseIndexingJobsParams struct {
	Limit    int32       `json:"limit"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) LeaseIndexingJobs(ctx context.Context, arg LeaseIndexingJobsParams) ([]IndexingJob, error) {
	rows, err := q.db.Query(ctx, leaseIndexingJobs, arg.Limit, arg.LockedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IndexingJob
	for rows.Next() {
		var i IndexingJob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Status,
			&i.Attempts,
			&i.MaxAttempts,
			&i.ErrorMessage,
			&i.LockedAt,
			&i.LockedBy,
			&i.RunAfter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIndexingJobFailed = `-- name: MarkIndexingJobFailed :one
UPDATE indexing_jobs
SET status = 'failed',
    error_message = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, document_id, status, attempts, max_attempts, error_message, locked_at, locked_by, run_after, created_at, updated_at
`

type MarkIndexingJobFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkIndexingJobFailed(ctx context.Context, arg MarkIndexingJobFailedParams) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, markIndexingJobFailed, arg.ID, arg.ErrorMessage)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIndexingJobRunning = `-- name: MarkIndexingJobRunning :one
UPDATE indexing_jobs
SET status = 'running',
    attempts = attempts + 1,
    locked_at = now(),
    locked_by = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, document_id, status, attempts, max_attempts, error_message, locked_at, locked_by, run_after, created_at, updated_at
`

type MarkIndexingJobRunningParams struct {
	ID       uuid.UUID   `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkIndexingJobRunning(ctx context.Context, arg MarkIndexingJobRunningParams) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, markIndexingJobRunning, arg.ID, arg.LockedBy)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIndexingJobSucceeded = `-- name: MarkIndexingJobSucceeded :one
UPDATE indexing_jobs
SET status = 'succeeded',
    error_message = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, document_id, status, attempts, max_attempts, error_message, locked_at, locked_by, run_after, created_at, updated_at
`

func (q *Queries) MarkIndexingJobSucceeded(ctx context.Context, id uuid.UUID) (IndexingJob, error) {
	row := q.db.QueryRow(ctx, markIndexingJobSucceeded, id)
	var i IndexingJob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ErrorMessage,
		&i.LockedAt,
		&i.LockedBy,
		&i.RunAfter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
