// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatMessage struct {
	ID             uuid.UUID          `json:"id"`
	SessionID      uuid.UUID          `json:"session_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	RewrittenQuery pgtype.Text        `json:"rewritten_query"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Chunk struct {
	ID           uuid.UUID          `json:"id"`
	DocumentID   uuid.UUID          `json:"document_id"`
	ChunkIndex   int32              `json:"chunk_index"`
	Content      string             `json:"content"`
	PageNumber   pgtype.Int4        `json:"page_number"`
	TokenCount   int32              `json:"token_count"`
	Metadata     []byte             `json:"metadata"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Citation struct {
	ID           uuid.UUID          `json:"id"`
	MessageID    uuid.UUID          `json:"message_id"`
	ChunkID      pgtype.UUID        `json:"chunk_id"`
	DocumentID   pgtype.UUID        `json:"document_id"`
	DocumentName string             `json:"document_name"`
	PageNumber   pgtype.Int4        `json:"page_number"`
	Excerpt      string             `json:"excerpt"`
	DenseScore   pgtype.Float8      `json:"dense_score"`
	LexicalRank  pgtype.Int4        `json:"lexical_rank"`
	FusedRank    pgtype.Int4        `json:"fused_rank"`
	RerankScore  pgtype.Float8      `json:"rerank_score"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID           uuid.UUID          `json:"id"`
	OwnerUserID  uuid.UUID          `json:"owner_user_id"`
	Filename     string             `json:"filename"`
	ContentType  string             `json:"content_type"`
	SizeBytes    int64              `json:"size_bytes"`
	Sha256       string             `json:"sha256"`
	RawBytes     []byte             `json:"raw_bytes"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type EvalRun struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Config       []byte             `json:"config"`
	Metrics      []byte             `json:"metrics"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IndexingJob struct {
	ID           uuid.UUID          `json:"id"`
	DocumentID   uuid.UUID          `json:"document_id"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	LockedAt     pgtype.Timestamptz `json:"locked_at"`
	LockedBy     pgtype.Text        `json:"locked_by"`
	RunAfter     pgtype.Timestamptz `json:"run_after"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type RetrievalTrace struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	SessionID        pgtype.UUID        `json:"session_id"`
	OriginalQuery    string             `json:"original_query"`
	RewrittenQuery   string             `json:"rewritten_query"`
	TopK             int32              `json:"top_k"`
	RerankerEnabled  bool               `json:"reranker_enabled"`
	DenseHits        []byte             `json:"dense_hits"`
	LexicalHits      []byte             `json:"lexical_hits"`
	FusedHits        []byte             `json:"fused_hits"`
	RerankedHits     []byte             `json:"reranked_hits"`
	PromptPreview    string             `json:"prompt_preview"`
	LatencyMs        int32              `json:"latency_ms"`
	EstimatedCostUsd string             `json:"estimated_cost_usd"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TokenCostEvent struct {
	ID               uuid.UUID          `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	ChatSessionID    pgtype.UUID        `json:"chat_session_id"`
	EvalRunID        pgtype.UUID        `json:"eval_run_id"`
	Provider         string             `json:"provider"`
	Model            string             `json:"model"`
	Operation        string             `json:"operation"`
	InputTokens      int32              `json:"input_tokens"`
	OutputTokens     int32              `json:"output_tokens"`
	EstimatedCostUsd string             `json:"estimated_cost_usd"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
